reminder:
  user: admin
  password: admin1
  local-database:
    active: true
    note-db: 'notebook-db'
    note-prefix: 'note-'
  external-database:
    active: false
    conf:
      host: mongodb.local
      port: 5432
      dbname: rmind-db01
      user: mongo01
      password: mongo011
      connect_timeout: 60
      sslmode: none